In [1]:
import pandas as pd

train_data_original = pd.read_csv("train_data.csv")
train_data_original


/var/folders/dm/ffp3qpxs1kx3v192xy1793wh0000gn/T/ipykernel_5782/2758797587.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


Index  Bankrupt?  \
0         0          0   
1         1          0   
2         2          0   
3         3          0   
4         4          0   
...     ...        ...   
5802   5802          0   
5803   5803          0   
5804   5804          0   
5805   5805          0   
5806   5806          0   

       ROA(C) before interest and depreciation before interest  \
0                                              0.450397          
1                                              0.530005          
2                                              0.571150          
3                                              0.483401          
4                                              0.510359          
...                                                 ...          
5802                                           0.507483          
5803                                           0.553795          
5804                                           0.491639          
5805                                           0.513626          
5806                                           0.537805          

       ROA(A) before interest and % after tax  \
0                                    0.504034   
1                                    0.572885   
2                                    0.620148   
3                                    0.556694   
4                                    0.537287   
...                                       ...   
5802                                 0.547263   
5803                                 0.636993   
5804                                 0.559693   
5805                                 0.573321   
5806                                 0.597253   

       ROA(B) before interest and depreciation after tax  \
0                                              0.506986    
1                                              0.574763    
2                                              0.624177    
3                                              0.536164    
4                                              0.552546    
...                                                 ...    
5802                                           0.553188    
5803                                           0.606671    
5804                                           0.541250    
5805                                           0.555758    
5806                                           0.582205    

       Operating Gross Margin   Realized Sales Gross Margin  \
0                    0.594640                      0.594640   
1                    0.605695                      0.605558   
2                    0.612275                      0.612282   
3                    0.602445                      0.602445   
4                    0.600023                      0.600023   
...                       ...                           ...   
5802                 0.596448                      0.596448   
5803                 0.648323                      0.648323   
5804                 0.597003                      0.597003   
5805                 0.646665                      0.646665   
5806                 0.635178                      0.635221   

       Operating Profit Rate   Pre-tax net Interest Rate  \
0                   0.998906                    0.797293   
1                   0.999058                    0.797512   
2                   0.999163                    0.797654   
3                   0.999035                    0.797458   
4                   0.999009                    0.797406   
...                      ...                         ...   
5802                0.998991                    0.797393   
5803                0.999388                    0.798010   
5804                0.998981                    0.797405   
5805                0.999066                    0.797506   
5806                0.999249                    0.797785   

       After-tax net Interest Rate  ...   Net Income to Total Assets  \
0                         0.809239  ... 

In [2]:
train_data_updated = pd.read_csv("train_data_updated.csv")
train_data_updated_with_bankrupt = pd.read_csv("train_data_updated_with_bankrupt.csv")

In [3]:
train_data_updated.drop('Unnamed: 0', axis=1, inplace=True)
train_data_updated

Operating Expense Rate   Cash Flow Per Share  \
0                    1.291763             -0.574968   
1                   -2.286852              0.248742   
2                   -1.898642              1.009234   
3                    1.182904             -2.727476   
4                    0.941069             -0.418016   
...                       ...                   ...   
5802                 0.554081              0.342006   
5803                 0.242819              0.512185   
5804                 0.678745              0.447200   
5805                 0.349424              1.257011   
5806                 0.193429              0.565234   

       Realized Sales Gross Profit Growth Rate   Net Value Growth Rate  \
0                                    -1.627254               -1.054253   
1                                     0.569580                0.722709   
2                                     0.794533                0.809529   
3                                     0.720634                0.422374   
4                                    -0.752851               -1.088834   
...                                        ...                     ...   
5802                                 -1.062682               -0.875449   
5803                                 -0.354526                0.879960   
5804                                 -0.922069               -1.086322   
5805                                  0.451866                1.469562   
5806                                 -0.230401               -0.907565   

       Cash Reinvestment %   Quick Ratio   Total debt/Total net worth  \
0                -0.416102     -0.384322                     0.068156   
1                 0.098690      0.226857                     0.069029   
2                 0.697808      0.747268                     0.032348   
3                -2.589341     -2.086978                     1.963339   
4                -0.705505      0.172439                     0.299363   
...                    ...           ...                          ...   
5802             -0.017300     -1.558050                     1.356404   
5803              1.167326      0.330407                    -0.615677   
5804             -0.423769      0.034308                     0.416649   
5805              1.013870      1.378413                     1.508370   
5806              0.305018      1.575788                    -1.417217   

       Long-term fund suitability ratio (A)  \
0                                 -0.836116   
1                                 -0.329645   
2                                 -0.142334   
3                                  0.575554   
4                                  0.768474   
...                                     ...   
5802                              -2.123688   
5803                              -0.683047   
5804                               1.005075   
5805                               1.032006   
5806                               0.152495   

       Inventory and accounts receivable/Net value  \
0                                        -0.492368   
1                                         0.773301   
2                                         0.311328   
3                                         2.355100   
4                                        -0.088187   
...                                            ...   
5802                                      0.663514   
5803                                     -1.113129   
5804                                      1.338185   
5805                                     -0.694933   
5806                                     -1.346547   

       Inventory Turnover Rate (times)  ...   Total expense/Assets  \
0                            -0.996796  ...              -0.425792   
1                            -1.699538  ...              -0.299494   
2                            -1.488469  ...              -0.318944   
3                             0.288010  ...              -1.117117   
4               

In [4]:
train_data_updated_with_bankrupt.drop('Unnamed: 0', axis=1, inplace=True)
train_data_updated_with_bankrupt

Operating Expense Rate   Cash Flow Per Share  \
0                    1.291763             -0.574968   
1                   -2.286852              0.248742   
2                   -1.898642              1.009234   
3                    1.182904             -2.727476   
4                    0.941069             -0.418016   
...                       ...                   ...   
5802                 0.554081              0.342006   
5803                 0.242819              0.512185   
5804                 0.678745              0.447200   
5805                 0.349424              1.257011   
5806                 0.193429              0.565234   

       Realized Sales Gross Profit Growth Rate   Net Value Growth Rate  \
0                                    -1.627254               -1.054253   
1                                     0.569580                0.722709   
2                                     0.794533                0.809529   
3                                     0.720634                0.422374   
4                                    -0.752851               -1.088834   
...                                        ...                     ...   
5802                                 -1.062682               -0.875449   
5803                                 -0.354526                0.879960   
5804                                 -0.922069               -1.086322   
5805                                  0.451866                1.469562   
5806                                 -0.230401               -0.907565   

       Cash Reinvestment %   Quick Ratio   Total debt/Total net worth  \
0                -0.416102     -0.384322                     0.068156   
1                 0.098690      0.226857                     0.069029   
2                 0.697808      0.747268                     0.032348   
3                -2.589341     -2.086978                     1.963339   
4                -0.705505      0.172439                     0.299363   
...                    ...           ...                          ...   
5802             -0.017300     -1.558050                     1.356404   
5803              1.167326      0.330407                    -0.615677   
5804             -0.423769      0.034308                     0.416649   
5805              1.013870      1.378413                     1.508370   
5806              0.305018      1.575788                    -1.417217   

       Long-term fund suitability ratio (A)  \
0                                 -0.836116   
1                                 -0.329645   
2                                 -0.142334   
3                                  0.575554   
4                                  0.768474   
...                                     ...   
5802                              -2.123688   
5803                              -0.683047   
5804                               1.005075   
5805                               1.032006   
5806                               0.152495   

       Inventory and accounts receivable/Net value  \
0                                        -0.492368   
1                                         0.773301   
2                                         0.311328   
3                                         2.355100   
4                                        -0.088187   
...                                            ...   
5802                                      0.663514   
5803                                     -1.113129   
5804                                      1.338185   
5805                                     -0.694933   
5806                                     -1.346547   

       Inventory Turnover Rate (times)  ...   Cash Turnover Rate  \
0                            -0.996796  ...             0.852965   
1                            -1.699538  ...             0.654325   
2                            -1.488469  ...            -1.362621   
3                             0.288010  ...             0.996796   
4                         

## PART 3

#### Part 3.1: Model to predict a group a company will likely belong too. 
#### Used a Random Forest Classifier as my supervised learning algorithm

In [5]:
index_numbers_df = train_data_updated_with_bankrupt['Index']

In [6]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


X = train_data_updated.drop('cluster', axis=1)
y = train_data_updated['cluster']

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Initialize the classifier
classifier = RandomForestClassifier(n_estimators=100, random_state=42)
classifier.fit(X_train_scaled, y_train)

# Prediction
y_pred = classifier.predict(X_test_scaled)


# Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Accuracy: 0.882960413080895
Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.95      0.92       102
           1       0.88      0.94      0.91       542
           2       0.86      0.71      0.77        85
           3       0.95      0.55      0.69        75
           4       0.88      0.90      0.89       358

    accuracy                           0.88      1162
   macro avg       0.89      0.81      0.84      1162
weighted avg       0.88      0.88      0.88      1162

Confusion Matrix:
 [[ 97   4   1   0   0]
 [  5 507   4   0  26]
 [  4  20  60   0   1]
 [  2   9   5  41  18]
 [  0  35   0   2 321]]


#### Filter my data to rows of cluster 4, drop the no feature columns, and split into X and y

In [7]:
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Load the data
train_data_original = pd.read_csv("train_data.csv")  # Update the path as necessary

# Assuming 'cluster_id' column indicates the cluster and is in the same dataframe as 'Bankrupt?'
# Filter the data for cluster 4
cluster_4_data = train_data_updated[train_data_updated['cluster'] == 4]


# Define features and target for cluster 4
X = cluster_4_data.drop(['cluster'], axis=1)  # Drop non-feature columns
y_1 = train_data_updated_with_bankrupt[train_data_updated_with_bankrupt['cluster'] == 4]
y = y_1['Bankrupt?']  # Ensure y is also filtered for cluster 4

#X.drop('Unnamed: 0', axis=1, inplace=True)
X


Operating Expense Rate  Cash Flow Per Share  \
3                   1.182904            -2.727476   
5                   0.688245            -1.161474   
6                   0.556725            -0.443877   
11                 -1.165915            -1.301058   
15                 -0.724932             0.148971   
...                      ...                  ...   
5791                0.057937            -0.939509   
5794               -0.159552            -0.784944   
5800               -1.898642            -1.281438   
5802                0.554081             0.342006   
5804                0.678745             0.447200   

      Realized Sales Gross Profit Growth Rate  Net Value Growth Rate  \
3                                    0.720634               0.422374   
5                                    1.640547               1.451347   
6                                    1.377352              -0.524228   
11                                  -1.009284              -1.135066   
15                                  -1.052039              -1.272378   
...                                       ...                    ...   
5791                                -1.799052               1.067796   
5794                                -0.837739              -0.805382   
5800                                 0.405191              -0.247966   
5802                                -1.062682              -0.875449   
5804                                -0.922069              -1.086322   

      Cash Reinvestment %  Quick Ratio  Total debt/Total net worth  \
3               -2.589341    -2.086978                    1.963339   
5               -0.864565     0.262990                    0.698184   
6               -0.164200    -1.619182                    1.255366   
11              -1.440840     0.143396                    0.041135   
15               0.971567    -0.921830                    0.840903   
...                   ...          ...                         ...   
5791            -0.799990    -1.174867                    0.850869   
5794            -0.611138    -1.361819                    0.957900   
5800            -1.035447     0.227331                    1.298278   
5802            -0.017300    -1.558050                    1.356404   
5804            -0.423769     0.034308                    0.416649   

      Long-term fund suitability ratio (A)  \
3                                 0.575554   
5                                 1.504363   
6                                -0.020805   
11                                0.814868   
15                               -0.888600   
...                                    ...   
5791                             -1.676610   
5794                             -0.454146   
5800                              0.554338   
5802                             -2.123688   
5804                              1.005075   

      Inventory and accounts receivable/Net value  \
3                                        2.355100   
5                                        0.244988   
6                                        1.400954   
11                                      -0.742653   
15                                       0.722808   
...                                           ...   
5791                                    -0.145676   
5794                                    -0.193498   
5800                                     1.386253   
5802                                     0.663514   
5804                                     1.338185   

      Inventory Turnover Rate (times)  ...  Total income/Total expense  \
3                            0.288010  ...                    0.324246   
5                            0.170946  ...                    1.781926   
6                            0.443047  ...                   -0.597406   
11                          -0.100152  ...                   -1.018003   
15                           1.253450  ...                   -0.987991   
...                          

#### split into train and test splits

In [8]:
# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)



#### Random Forest Classifier

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Set up Random Forest with adjusted class weight for imbalance
rf_model = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)

# Fit the model on the training data
rf_model.fit(X_train, y_train)

# Predicting the Test set results
y_pred_rf = rf_model.predict(X_test)

# Evaluate the model
accuracy_rf = accuracy_score(y_test, y_pred_rf)
conf_matrix_rf = confusion_matrix(y_test, y_pred_rf)
print("Accuracy:", accuracy_rf)
print("Confusion Matrix:\n", conf_matrix_rf)
print(classification_report(y_test, y_pred_rf))


Accuracy: 0.9397163120567376
Confusion Matrix:
 [[528   2]
 [ 32   2]]
              precision    recall  f1-score   support

           0       0.94      1.00      0.97       530
           1       0.50      0.06      0.11        34

    accuracy                           0.94       564
   macro avg       0.72      0.53      0.54       564
weighted avg       0.92      0.94      0.92       564



#### LOGISTIC REGRESSION (Non Parametric Model #2)

In [10]:
#LOGISTIC REGRESSION
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

# Assuming 'X' and 'y' have been defined after dropping 'Index' and setting 'Bankrupt?' as target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale features (important for logistic regression performance)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Initialize Logistic Regression with class weight balancing
lr_model = LogisticRegression(class_weight='balanced', random_state=42)
lr_model.fit(X_train_scaled, y_train)

# Prediction and Evaluation
y_pred_lr = lr_model.predict(X_test_scaled)

accuracy = accuracy_score(y_test, y_pred_lr)
print("Accuracy:", accuracy)
print("Logistic Regression Classification Report:\n", classification_report(y_test, y_pred_lr))
print("Logistic Regression Confusion Matrix:\n", confusion_matrix(y_test, y_pred_lr))




Accuracy: 0.8297872340425532
Logistic Regression Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.84      0.90       350
           1       0.25      0.73      0.37        26

    accuracy                           0.83       376
   macro avg       0.61      0.78      0.64       376
weighted avg       0.93      0.83      0.86       376

Logistic Regression Confusion Matrix:
 [[293  57]
 [  7  19]]


#### SVM (Non Paramteirc Model #3)

In [11]:
from sklearn.svm import SVC

# Initialize SVM with class weight balancing
svm = SVC(class_weight='balanced', kernel='linear', random_state=42)  # Consider 'rbf' for non-linear
svm.fit(X_train_scaled, y_train)

# Prediction and Evaluation
svm_predictions = svm.predict(X_test_scaled)
accuracy = accuracy_score(y_test, svm_predictions)
print("Accuracy:", accuracy)
print("SVM Classification Report:\n", classification_report(y_test, svm_predictions))
print("SVM Confusion Matrix:\n", confusion_matrix(y_test, svm_predictions))

Accuracy: 0.824468085106383
SVM Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.83      0.90       350
           1       0.25      0.77      0.38        26

    accuracy                           0.82       376
   macro avg       0.61      0.80      0.64       376
weighted avg       0.93      0.82      0.86       376

SVM Confusion Matrix:
 [[290  60]
 [  6  20]]


### Stacked Model Configuration

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import StackingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import SMOTE
import numpy as np
from sklearn.naive_bayes import GaussianNB


# Assuming X and y are defined and are your initial datasets

# Split the data into training, validation, and test sets
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.30, random_state=42)  # Split into train and temp
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)  # Split temp into val and test

# Train base models on the training data
rf_model.fit(X_train, y_train)
lr_model.fit(X_train, y_train) 
svm.fit(X_train, y_train) 

# Create meta-features using the validation set
probs_rf_val = rf_model.predict_proba(X_val)[:, 1]
probs_lr_val = lr_model.predict_proba(X_val)[:, 1]
probs_svm_val = svm.decision_function(X_val)

meta_features_val = np.column_stack([probs_rf_val, probs_lr_val, probs_svm_val])

# Train the meta-model on the validation meta-features
meta_model = GaussianNB()
meta_model.fit(meta_features_val, y_val)

# Create meta-features for the test set
probs_rf_test = rf_model.predict_proba(X_test)[:, 1]
probs_lr_test = lr_model.predict_proba(X_test)[:, 1]
probs_svm_test = svm.decision_function(X_test)

meta_features_test = np.column_stack([probs_rf_test, probs_lr_test, probs_svm_test])

# Predict using the meta-model on the test set meta-features
final_predictions = meta_model.predict(meta_features_test)

# Evaluate the model on the test set
print("Stacked Model Classification Report:\n", classification_report(y_test, final_predictions))
print("Stacked Model Confusion Matrix:\n", confusion_matrix(y_test, final_predictions))


Stacked Model Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.89      0.92       264
           1       0.23      0.50      0.32        18

    accuracy                           0.86       282
   macro avg       0.60      0.69      0.62       282
weighted avg       0.92      0.86      0.88       282

Stacked Model Confusion Matrix:
 [[234  30]
 [  9   9]]


/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


### PART 4

In [13]:
data = pd.read_csv('train_data_updated_with_bankrupt.csv')
data.drop('Unnamed: 0', axis=1, inplace=True)
data

Operating Expense Rate   Cash Flow Per Share  \
0                    1.291763             -0.574968   
1                   -2.286852              0.248742   
2                   -1.898642              1.009234   
3                    1.182904             -2.727476   
4                    0.941069             -0.418016   
...                       ...                   ...   
5802                 0.554081              0.342006   
5803                 0.242819              0.512185   
5804                 0.678745              0.447200   
5805                 0.349424              1.257011   
5806                 0.193429              0.565234   

       Realized Sales Gross Profit Growth Rate   Net Value Growth Rate  \
0                                    -1.627254               -1.054253   
1                                     0.569580                0.722709   
2                                     0.794533                0.809529   
3                                     0.720634                0.422374   
4                                    -0.752851               -1.088834   
...                                        ...                     ...   
5802                                 -1.062682               -0.875449   
5803                                 -0.354526                0.879960   
5804                                 -0.922069               -1.086322   
5805                                  0.451866                1.469562   
5806                                 -0.230401               -0.907565   

       Cash Reinvestment %   Quick Ratio   Total debt/Total net worth  \
0                -0.416102     -0.384322                     0.068156   
1                 0.098690      0.226857                     0.069029   
2                 0.697808      0.747268                     0.032348   
3                -2.589341     -2.086978                     1.963339   
4                -0.705505      0.172439                     0.299363   
...                    ...           ...                          ...   
5802             -0.017300     -1.558050                     1.356404   
5803              1.167326      0.330407                    -0.615677   
5804             -0.423769      0.034308                     0.416649   
5805              1.013870      1.378413                     1.508370   
5806              0.305018      1.575788                    -1.417217   

       Long-term fund suitability ratio (A)  \
0                                 -0.836116   
1                                 -0.329645   
2                                 -0.142334   
3                                  0.575554   
4                                  0.768474   
...                                     ...   
5802                              -2.123688   
5803                              -0.683047   
5804                               1.005075   
5805                               1.032006   
5806                               0.152495   

       Inventory and accounts receivable/Net value  \
0                                        -0.492368   
1                                         0.773301   
2                                         0.311328   
3                                         2.355100   
4                                        -0.088187   
...                                            ...   
5802                                      0.663514   
5803                                     -1.113129   
5804                                      1.338185   
5805                                     -0.694933   
5806                                     -1.346547   

       Inventory Turnover Rate (times)  ...   Cash Turnover Rate  \
0                            -0.996796  ...             0.852965   
1                            -1.699538  ...             0.654325   
2                            -1.488469  ...            -1.362621   
3                             0.288010  ...             0.996796   
4                         

In [14]:
data_change = pd.read_csv('train_data_updated_with_bankrupt.csv')
data_change.drop(['Index', ' Net Income Flag', ' Inventory Turnover Rate (times)', ' Operating Expense Rate', ' Realized Sales Gross Profit Growth Rate', ' Total assets to GNP price', ' Cash Flow to Total Assets', ' Net Value Growth Rate', ' Total income/Total expense', ' Current Asset Turnover Rate', ' Long-term fund suitability ratio (A)', ' Operating profit per person', ' Total expense/Assets', ' Retained Earnings to Total Assets', ' Cash Reinvestment %', ' Cash Flow to Liability'], axis=1, inplace=True)
data_change.to_csv("train_data_15_features.csv")

In [15]:
arr = [' Bankrupt?', ' Net Income Flag', ' Inventory Turnover Rate (times)', ' Operating Expense Rate', ' Realized Sales Gross Profit Growth Rate', ' Total assets to GNP price', ' Cash Flow to Total Assets', ' Net Value Growth Rate', ' Total income/Total expense', ' Current Asset Turnover Rate', ' Long-term fund suitability ratio (A)']

# Load your dataset
data2 = pd.read_csv('train_data_updated_with_bankrupt.csv')
X = data2.drop(['Unnamed: 0','Bankrupt?', 'Index', ' Net Income Flag', ' Inventory Turnover Rate (times)', ' Operating Expense Rate', ' Realized Sales Gross Profit Growth Rate', ' Total assets to GNP price', ' Cash Flow to Total Assets', ' Net Value Growth Rate', ' Total income/Total expense', ' Current Asset Turnover Rate', ' Long-term fund suitability ratio (A)'], axis=1, inplace=False)
y = data['Bankrupt?']


X

Cash Flow Per Share   Cash Reinvestment %   Quick Ratio  \
0                -0.574968             -0.416102     -0.384322   
1                 0.248742              0.098690      0.226857   
2                 1.009234              0.697808      0.747268   
3                -2.727476             -2.589341     -2.086978   
4                -0.418016             -0.705505      0.172439   
...                    ...                   ...           ...   
5802              0.342006             -0.017300     -1.558050   
5803              0.512185              1.167326      0.330407   
5804              0.447200             -0.423769      0.034308   
5805              1.257011              1.013870      1.378413   
5806              0.565234              0.305018      1.575788   

       Total debt/Total net worth  \
0                        0.068156   
1                        0.069029   
2                        0.032348   
3                        1.963339   
4                        0.299363   
...                           ...   
5802                     1.356404   
5803                    -0.615677   
5804                     0.416649   
5805                     1.508370   
5806                    -1.417217   

       Inventory and accounts receivable/Net value  \
0                                        -0.492368   
1                                         0.773301   
2                                         0.311328   
3                                         2.355100   
4                                        -0.088187   
...                                            ...   
5802                                      0.663514   
5803                                     -1.113129   
5804                                      1.338185   
5805                                     -0.694933   
5806                                     -1.346547   

       Operating profit per person   Working Capital to Total Assets  \
0                        -1.124379                         -0.591520   
1                         0.392161                          0.325152   
2                         0.809055                          0.520889   
3                         1.014449                          0.131043   
4                         1.005758                         -0.015258   
...                            ...                               ...   
5802                      0.203982                         -1.746742   
5803                      0.470318                          0.179679   
5804                      0.829748                          1.159750   
5805                     -0.608119                          1.125411   
5806                      0.733186                          0.814621   

       Quick Assets/Total Assets   Current Assets/Total Assets  \
0                      -1.215923                     -1.146342   
1                       0.436589                      0.389028   
2                       0.314223                      0.083191   
3                      -1.956603                      1.515581   
4                       0.993073                      0.400289   
...                          ...                           ...   
5802                   -0.662418                     -0.468627   
5803                    0.247066                     -0.000551   
5804                    0.804550                      1.876914   
5805                    0.842932                      0.333778   
5806                    0.350669                     -0.135545   

       Cash/Total Assets  ...   Cash/Current Liability  \
0              -0.070169  ...                 0.274431   
1              -0.130464  ...                -0.283603   
2               0.560333  ...                 0.619910   
3              -0.355378  ...                -0.917495   
4               1.183910  ...                 0.609456   
...                  ...  ...                      ...   
5802           -0.930553  ...                -1.260468  

In [16]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import StandardScaler

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardizing the training data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)  

# SMOTE for handling class imbalance on training data only
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_scaled, y_train)

# Stratified k-fold cross-validation setup
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Define the GaussianNB model
gaussian_nb = GaussianNB()

# Parameters grid for hyperparameter tuning
param_grid = {
    'var_smoothing': np.logspace(0,-9, num=100)
}

# GridSearchCV for hyperparameter tuning within the cross-validation
grid_search = GridSearchCV(
    estimator=gaussian_nb,
    param_grid=param_grid,
    scoring='recall',  # Can use 'accuracy' or other metrics
    n_jobs=-1,
    cv=skf,
    verbose=3
)

# Fit GridSearchCV on the resampled training data
grid_search.fit(X_train_resampled, y_train_resampled)

# Extract the best model
best_model = grid_search.best_estimator_

# Evaluate the best model on the untouched test set
predictions = best_model.predict(X_test_scaled)
accuracy = accuracy_score(y_test, predictions)
cm = confusion_matrix(y_test, predictions)
cr = classification_report(y_test, predictions)

print("Final Model Performance on the Test Set:")
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", cm)
print(cr)


Fitting 5 folds for each of 100 candidates, totalling 500 fits
Final Model Performance on the Test Set:
Accuracy: 0.7271944922547332
Confusion Matrix:
 [[811 313]
 [  4  34]]
              precision    recall  f1-score   support

           0       1.00      0.72      0.84      1124
           1       0.10      0.89      0.18        38

    accuracy                           0.73      1162
   macro avg       0.55      0.81      0.51      1162
weighted avg       0.97      0.73      0.81      1162

[CV 3/5] END ..var_smoothing=0.8111308307896871;, score=0.936 total time=   0.0s
[CV 3/5] END var_smoothing=0.0003511191734215131;, score=0.886 total time=   0.0s
[CV 4/5] END var_smoothing=0.0003511191734215131;, score=0.901 total time=   0.0s
[CV 5/5] END var_smoothing=0.0003511191734215131;, score=0.874 total time=   0.0s
[CV 1/5] END var_smoothing=0.0002848035868435802;, score=0.892 total time=   0.0s
[CV 2/5] END var_smoothing=0.0002848035868435802;, score=0.891 total time=   0.0s
[CV 3/5

[CV 2/5] END .................var_smoothing=1.0;, score=0.934 total time=   0.0s
[CV 5/5] END ..var_smoothing=0.8111308307896871;, score=0.923 total time=   0.0s
[CV 2/5] END ...var_smoothing=0.657933224657568;, score=0.931 total time=   0.0s
[CV 4/5] END ...var_smoothing=0.657933224657568;, score=0.935 total time=   0.0s
[CV 1/5] END ...var_smoothing=0.533669923120631;, score=0.923 total time=   0.0s
[CV 5/5] END ...var_smoothing=0.533669923120631;, score=0.918 total time=   0.0s
[CV 3/5] END ..var_smoothing=0.3511191734215131;, score=0.914 total time=   0.0s
[CV 5/5] END .var_smoothing=0.23101297000831597;, score=0.905 total time=   0.0s
[CV 1/5] END .var_smoothing=0.15199110829529336;, score=0.910 total time=   0.0s
[CV 4/5] END .................var_smoothing=0.1;, score=0.914 total time=   0.0s
[CV 5/5] END .................var_smoothing=0.1;, score=0.891 total time=   0.0s
[CV 4/5] END ..var_smoothing=0.0657933224657568;, score=0.910 total time=   0.0s
[CV 5/5] END ..var_smoothing

[CV 4/5] END .................var_smoothing=1.0;, score=0.942 total time=   0.0s
[CV 2/5] END ..var_smoothing=0.3511191734215131;, score=0.919 total time=   0.0s
[CV 3/5] END ..var_smoothing=0.2848035868435802;, score=0.912 total time=   0.0s
[CV 3/5] END .var_smoothing=0.23101297000831597;, score=0.909 total time=   0.0s
[CV 3/5] END ..var_smoothing=0.1873817422860384;, score=0.906 total time=   0.0s
[CV 3/5] END .var_smoothing=0.15199110829529336;, score=0.903 total time=   0.0s
[CV 5/5] END .var_smoothing=0.12328467394420659;, score=0.895 total time=   0.0s
[CV 1/5] END .................var_smoothing=0.1;, score=0.906 total time=   0.0s
[CV 1/5] END ..var_smoothing=0.0533669923120631;, score=0.899 total time=   0.0s
[CV 2/5] END ..var_smoothing=0.0533669923120631;, score=0.897 total time=   0.0s
[CV 4/5] END .var_smoothing=0.04328761281083057;, score=0.906 total time=   0.0s
[CV 5/5] END .var_smoothing=0.04328761281083057;, score=0.881 total time=   0.0s
[CV 2/5] END .var_smoothing=

[CV 1/5] END .................var_smoothing=1.0;, score=0.931 total time=   0.0s
[CV 4/5] END ..var_smoothing=0.8111308307896871;, score=0.938 total time=   0.0s
[CV 1/5] END ...var_smoothing=0.657933224657568;, score=0.923 total time=   0.0s
[CV 3/5] END ...var_smoothing=0.657933224657568;, score=0.932 total time=   0.0s
[CV 5/5] END ...var_smoothing=0.657933224657568;, score=0.920 total time=   0.0s
[CV 2/5] END ...var_smoothing=0.533669923120631;, score=0.926 total time=   0.0s
[CV 2/5] END .var_smoothing=0.43287612810830584;, score=0.924 total time=   0.0s
[CV 5/5] END ..var_smoothing=0.2848035868435802;, score=0.907 total time=   0.0s
[CV 2/5] END .var_smoothing=0.15199110829529336;, score=0.911 total time=   0.0s
[CV 4/5] END .var_smoothing=0.15199110829529336;, score=0.918 total time=   0.0s
[CV 5/5] END .var_smoothing=0.15199110829529336;, score=0.895 total time=   0.0s
[CV 3/5] END .var_smoothing=0.08111308307896872;, score=0.897 total time=   0.0s
[CV 4/5] END .var_smoothing=