In [1]:
import pandas as pd
import numpy as np

train_data = pd.read_csv("train_data.csv")
train_data


/var/folders/dm/ffp3qpxs1kx3v192xy1793wh0000gn/T/ipykernel_5694/1307912503.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


Index  Bankrupt?  \
0         0          0   
1         1          0   
2         2          0   
3         3          0   
4         4          0   
...     ...        ...   
5802   5802          0   
5803   5803          0   
5804   5804          0   
5805   5805          0   
5806   5806          0   

       ROA(C) before interest and depreciation before interest  \
0                                              0.450397          
1                                              0.530005          
2                                              0.571150          
3                                              0.483401          
4                                              0.510359          
...                                                 ...          
5802                                           0.507483          
5803                                           0.553795          
5804                                           0.491639          
5805                                           0.513626          
5806                                           0.537805          

       ROA(A) before interest and % after tax  \
0                                    0.504034   
1                                    0.572885   
2                                    0.620148   
3                                    0.556694   
4                                    0.537287   
...                                       ...   
5802                                 0.547263   
5803                                 0.636993   
5804                                 0.559693   
5805                                 0.573321   
5806                                 0.597253   

       ROA(B) before interest and depreciation after tax  \
0                                              0.506986    
1                                              0.574763    
2                                              0.624177    
3                                              0.536164    
4                                              0.552546    
...                                                 ...    
5802                                           0.553188    
5803                                           0.606671    
5804                                           0.541250    
5805                                           0.555758    
5806                                           0.582205    

       Operating Gross Margin   Realized Sales Gross Margin  \
0                    0.594640                      0.594640   
1                    0.605695                      0.605558   
2                    0.612275                      0.612282   
3                    0.602445                      0.602445   
4                    0.600023                      0.600023   
...                       ...                           ...   
5802                 0.596448                      0.596448   
5803                 0.648323                      0.648323   
5804                 0.597003                      0.597003   
5805                 0.646665                      0.646665   
5806                 0.635178                      0.635221   

       Operating Profit Rate   Pre-tax net Interest Rate  \
0                   0.998906                    0.797293   
1                   0.999058                    0.797512   
2                   0.999163                    0.797654   
3                   0.999035                    0.797458   
4                   0.999009                    0.797406   
...                      ...                         ...   
5802                0.998991                    0.797393   
5803                0.999388                    0.798010   
5804                0.998981                    0.797405   
5805                0.999066                    0.797506   
5806                0.999249                    0.797785   

       After-tax net Interest Rate  ...   Net Income to Total Assets  \
0                         0.809239  ... 

In [2]:
import pandas as pd 
train_data_original = pd.read_csv("train_data.csv")
train_data_updated = pd.read_csv("train_data_22_features.csv")
train_data_updated = train_data_updated.drop(['Unnamed: 0.1', 'Unnamed: 0'], axis=1)
# Add the 'Bankrupt?' column from the original dataframe to the updated dataframe using indices
# train_data_updated_with_bankrupt = train_data_updated.merge(train_data_original[['Index', 'Bankrupt?']], left_index=True, right_index=True, how='left')
# train_data_updated_with_bankrupt.to_csv("train_data_updated_with_bankrupt.csv")
train_data_updated

Cash Flow Per Share   Cash Reinvestment %   Quick Ratio  \
0                -0.574968             -0.416102     -0.384322   
1                 0.248742              0.098690      0.226857   
2                 1.009234              0.697808      0.747268   
3                -2.727476             -2.589341     -2.086978   
4                -0.418016             -0.705505      0.172439   
...                    ...                   ...           ...   
5802              0.342006             -0.017300     -1.558050   
5803              0.512185              1.167326      0.330407   
5804              0.447200             -0.423769      0.034308   
5805              1.257011              1.013870      1.378413   
5806              0.565234              0.305018      1.575788   

       Total debt/Total net worth  \
0                        0.068156   
1                        0.069029   
2                        0.032348   
3                        1.963339   
4                        0.299363   
...                           ...   
5802                     1.356404   
5803                    -0.615677   
5804                     0.416649   
5805                     1.508370   
5806                    -1.417217   

       Inventory and accounts receivable/Net value  \
0                                        -0.492368   
1                                         0.773301   
2                                         0.311328   
3                                         2.355100   
4                                        -0.088187   
...                                            ...   
5802                                      0.663514   
5803                                     -1.113129   
5804                                      1.338185   
5805                                     -0.694933   
5806                                     -1.346547   

       Operating profit per person   Working Capital to Total Assets  \
0                        -1.124379                         -0.591520   
1                         0.392161                          0.325152   
2                         0.809055                          0.520889   
3                         1.014449                          0.131043   
4                         1.005758                         -0.015258   
...                            ...                               ...   
5802                      0.203982                         -1.746742   
5803                      0.470318                          0.179679   
5804                      0.829748                          1.159750   
5805                     -0.608119                          1.125411   
5806                      0.733186                          0.814621   

       Quick Assets/Total Assets   Current Assets/Total Assets  \
0                      -1.215923                     -1.146342   
1                       0.436589                      0.389028   
2                       0.314223                      0.083191   
3                      -1.956603                      1.515581   
4                       0.993073                      0.400289   
...                          ...                           ...   
5802                   -0.662418                     -0.468627   
5803                    0.247066                     -0.000551   
5804                    0.804550                      1.876914   
5805                    0.842932                      0.333778   
5806                    0.350669                     -0.135545   

       Cash/Total Assets  ...   Current Liability to Assets  \
0              -0.070169  ...                     -0.757313   
1              -0.130464  ...                      0.354290   
2               0.560333  ...                     -0.393249   
3              -0.355378  ...                      1.752683   
4               1.183910  ...                      0.751469   
...                  ...  ...                           ...   
5802           -0.930

# SECTION 3

In [3]:
# index_numbers_df = train_data_updated_with_bankrupt['Index']

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Assuming 'cluster_id' column indicates the cluster and is in the same dataframe as 'Bankrupt?'
# Filter the data for cluster 2 and 3
cluster_2_data = train_data_updated[train_data_updated['cluster'] == 2]
cluster_3_data = train_data_updated[train_data_updated['cluster'] == 3]

# Define features and target for cluster 2
X2 = cluster_2_data.drop(['cluster', 'Bankrupt?'], axis=1)  # Drop non-feature columns
y2 = cluster_2_data['Bankrupt?']  # Ensure y is also filtered for cluster 2

# Define features and target for cluster 3
X3 = cluster_3_data.drop(['cluster', 'Bankrupt?'], axis=1)  # Drop non-feature columns
y3 = cluster_3_data['Bankrupt?']  # Ensure y is also filtered for cluster 3


In [5]:
X2

Cash Flow Per Share  Cash Reinvestment %  Quick Ratio  \
14              -1.059751            -0.862225     1.013727   
51              -1.290609            -1.517233     2.509943   
52              -0.893320            -0.778210     1.704471   
62               0.144410             0.105243     2.526289   
75              -2.436559            -2.490188    -0.344399   
...                   ...                  ...          ...   
5769             0.158358            -0.388624     1.590952   
5779            -0.422946             0.023298     0.138102   
5787            -1.681328            -1.504602     1.002035   
5788            -0.236090            -0.743975     0.996844   
5795            -0.353458            -0.249000     1.499747   

      Total debt/Total net worth  Inventory and accounts receivable/Net value  \
14                     -0.921341                                    -0.259358   
51                     -2.297253                                    -0.976191   
52                     -2.110864                                    -1.172869   
62                     -1.550489                                    -0.609930   
75                     -0.379795                                     0.952360   
...                          ...                                          ...   
5769                    0.024746                                    -1.612801   
5779                   -0.732835                                    -2.436699   
5787                   -0.517407                                     0.252622   
5788                   -1.739104                                    -0.463811   
5795                   -1.314702                                    -0.345762   

      Operating profit per person  Working Capital to Total Assets  \
14                      -0.626318                         1.707713   
51                      -1.231679                         2.696756   
52                      -1.285437                         1.025278   
62                      -1.851772                         1.096787   
75                      -1.161234                         1.581112   
...                           ...                              ...   
5769                     0.406552                        -0.117280   
5779                    -1.481672                        -0.989522   
5787                     1.032025                         1.265542   
5788                     1.057174                         0.333352   
5795                     0.795909                         1.522497   

      Quick Assets/Total Assets  Current Assets/Total Assets  \
14                     0.865368                     1.277802   
51                     2.410053                     1.582461   
52                     0.408995                     0.030260   
62                    -0.670691                    -0.143449   
75                    -0.098141                     1.770449   
...                         ...                          ...   
5769                  -0.861178                    -1.353078   
5779                  -1.559126                    -2.175254   
5787                   1.660499                     1.013202   
5788                  -0.519548                    -0.544393   
5795                   1.148980                     0.782891   

      Cash/Total Assets  Quick Assets/Current Liability  \
14             1.900439                        1.024476   
51            -0.777537                        2.553293   
52             1.494357                        1.759102   
62             0.923720                        2.588217   
75             0.138594                       -0.212671   
...                 ...                             ...   
5769           0.125268                        1.575734   
5779          -0.888829                        0.056598   
5787           0.020639                        1.001480   
5788          -0.356667                        1.008373   
5795           0.

# Section 3_2 Cluster 2

In [6]:
from sklearn.neighbors import KNeighborsRegressor as KNN
from sklearn.neural_network import MLPRegressor
from sklearn.svm import SVR
# Initialize base learners
knn = KNN(n_neighbors=5)  # Using 5 nearest neighbors
mlp = MLPRegressor()
svr = SVR(kernel='rbf')  # Using radial basis function kernel for SVR

X_train, X_temp, y_train, y_temp = train_test_split(X2, y2, test_size=0.4, random_state=42)

X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

# Fit base learners on training data
knn.fit(X_train, y_train)
mlp.fit(X_train, y_train)
svr.fit(X_train, y_train)

    
# Generate predictions on training and test data
knn_train_pred = knn.predict(X_val)
mlp_train_pred = mlp.predict(X_val)
svr_train_pred = svr.predict(X_val)

threshold = 0.5
knn_train_pred_bin = (knn_train_pred > threshold).astype(int)
mlp_train_pred_bin = (mlp_train_pred > threshold).astype(int)
svr_train_pred_bin = (svr_train_pred > threshold).astype(int)

# Evaluate the model
accuracy = accuracy_score(y_val,knn_train_pred_bin)
conf_matrix = confusion_matrix(y_val,knn_train_pred_bin)
print("Cluster2 KNN:\n Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print(classification_report(y_val,knn_train_pred_bin))

accuracy = accuracy_score(y_val,mlp_train_pred_bin)
conf_matrix = confusion_matrix(y_val,mlp_train_pred_bin)
print("Cluster2 MLP:\n Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print(classification_report(y_val,mlp_train_pred_bin))

accuracy = accuracy_score(y_val,svr_train_pred_bin)
conf_matrix = confusion_matrix(y_val,svr_train_pred_bin)
print("Cluster2 svr:\n Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print(classification_report(y_val,svr_train_pred_bin))


Cluster2 KNN:
 Accuracy: 0.9883720930232558
Confusion Matrix:
 [[85  0]
 [ 1  0]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99        85
           1       0.00      0.00      0.00         1

    accuracy                           0.99        86
   macro avg       0.49      0.50      0.50        86
weighted avg       0.98      0.99      0.98        86

Cluster2 MLP:
 Accuracy: 0.9883720930232558
Confusion Matrix:
 [[85  0]
 [ 1  0]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99        85
           1       0.00      0.00      0.00         1

    accuracy                           0.99        86
   macro avg       0.49      0.50      0.50        86
weighted avg       0.98      0.99      0.98        86

Cluster2 svr:
 Accuracy: 0.9883720930232558
Confusion Matrix:
 [[85  0]
 [ 1  0]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99  

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  

In [7]:
# Stack these probabilities as new features for meta-model

knn_train = knn.predict(X_val)
mlp_train = mlp.predict(X_val)
svr_train = svr.predict(X_val)

meta_features_val = np.column_stack([knn_train, mlp_train, svr_train])
print(meta_features_val.shape)

from sklearn.naive_bayes import GaussianNB

# Step 4: Train Meta-Model

# We use GNB as the meta-model
meta_model = GaussianNB()
meta_model.fit(meta_features_val, y_val)  


knn_test = knn.predict(X_test)
mlp_test = mlp.predict(X_test)
svr_test = svr.predict(X_test)

meta_features_test = np.column_stack([knn_test, mlp_test, svr_test])

# Step 5: Predict using Meta-Model
final_predictions = meta_model.predict(meta_features_test)
print(len(final_predictions))

# Evaluation
accuracy = accuracy_score(y_test,final_predictions)
print("Cluster 2 Stacked Model:\n Accuracy:", accuracy)
print("Classification Report:\n", classification_report(y_test, final_predictions))
print("Stacked Model Confusion Matrix:\n", confusion_matrix(y_test, final_predictions))

(86, 3)
86
Cluster 2 Stacked Model:
 Accuracy: 0.9651162790697675
Classification Report:
               precision    recall  f1-score   support

           0       0.97      1.00      0.98        83
           1       0.00      0.00      0.00         3

    accuracy                           0.97        86
   macro avg       0.48      0.50      0.49        86
weighted avg       0.93      0.97      0.95        86

Stacked Model Confusion Matrix:
 [[83  0]
 [ 3  0]]


/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  

# Cluster 3

In [8]:
from sklearn.neighbors import KNeighborsRegressor as KNN
from sklearn.neural_network import MLPRegressor
from sklearn.svm import SVR
# Initialize base learners
knn = KNN(n_neighbors=5)  # Using 5 nearest neighbors
mlp = MLPRegressor()
svr = SVR(kernel='rbf')  # Using radial basis function kernel for SVR

X_train, X_temp, y_train, y_temp = train_test_split(X3, y3, test_size=0.4, random_state=42)

X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

# Fit base learners on training data
knn.fit(X_train, y_train)
mlp.fit(X_train, y_train)
svr.fit(X_train, y_train)

    
# Generate predictions on training and test data
knn_train_pred = knn.predict(X_val)
mlp_train_pred = mlp.predict(X_val)
svr_train_pred = svr.predict(X_val)


threshold = 0.5
knn_train_pred_bin = (knn_train_pred > threshold).astype(int)
mlp_train_pred_bin = (mlp_train_pred > threshold).astype(int)
svr_train_pred_bin = (svr_train_pred > threshold).astype(int)

# Evaluate the model
accuracy = accuracy_score(y_val,knn_train_pred_bin)
conf_matrix = confusion_matrix(y_val,knn_train_pred_bin)
print("Cluster3 KNN:\n Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print(classification_report(y_val,knn_train_pred_bin))

accuracy = accuracy_score(y_val,mlp_train_pred_bin)
conf_matrix = confusion_matrix(y_val,mlp_train_pred_bin)
print("Cluster3 MLP:\n Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print(classification_report(y_val,mlp_train_pred_bin))

accuracy = accuracy_score(y_val,svr_train_pred_bin)
conf_matrix = confusion_matrix(y_val,svr_train_pred_bin)
print("Cluster3 svr:\n Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print(classification_report(y_val,svr_train_pred_bin))


Cluster3 KNN:
 Accuracy: 0.84375
Confusion Matrix:
 [[52  3]
 [ 7  2]]
              precision    recall  f1-score   support

           0       0.88      0.95      0.91        55
           1       0.40      0.22      0.29         9

    accuracy                           0.84        64
   macro avg       0.64      0.58      0.60        64
weighted avg       0.81      0.84      0.82        64

Cluster3 MLP:
 Accuracy: 0.859375
Confusion Matrix:
 [[51  4]
 [ 5  4]]
              precision    recall  f1-score   support

           0       0.91      0.93      0.92        55
           1       0.50      0.44      0.47         9

    accuracy                           0.86        64
   macro avg       0.71      0.69      0.69        64
weighted avg       0.85      0.86      0.86        64

Cluster3 svr:
 Accuracy: 0.875
Confusion Matrix:
 [[53  2]
 [ 6  3]]
              precision    recall  f1-score   support

           0       0.90      0.96      0.93        55
           1       0.60  

In [9]:
# Stack these probabilities as new features for meta-model

knn_train = knn.predict(X_val)
mlp_train = mlp.predict(X_val)
svr_train = svr.predict(X_val)
meta_features_val = np.column_stack([knn_train, mlp_train, svr_train])

from sklearn.naive_bayes import GaussianNB

# Step 4: Train Meta-Model

# We use GNB as the meta-model
meta_model = GaussianNB()
meta_model.fit(meta_features_val, y_val)  


knn_test = knn.predict(X_test)
mlp_test = mlp.predict(X_test)
svr_test = svr.predict(X_test)

meta_features_test = np.column_stack([knn_test, mlp_test, svr_test])

# Step 5: Predict using Meta-Model
final_predictions = meta_model.predict(meta_features_test)

# Evaluation
accuracy = accuracy_score(y_test,final_predictions)
print("Cluster 3 Stacked Model:\n Accuracy:", accuracy)
print("Classification Report:\n", classification_report(y_test, final_predictions))
print("Stacked Model Confusion Matrix:\n", confusion_matrix(y_test, final_predictions))

Cluster 3 Stacked Model:
 Accuracy: 0.8615384615384616
Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.95      0.92        55
           1       0.57      0.40      0.47        10

    accuracy                           0.86        65
   macro avg       0.73      0.67      0.70        65
weighted avg       0.85      0.86      0.85        65

Stacked Model Confusion Matrix:
 [[52  3]
 [ 6  4]]


### Section 4

In [10]:
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd
import numpy as np

# Load dataset
data = pd.read_csv('train_data_22_features.csv')

# Define features and target
X = data.drop('Bankrupt?', axis=1)
y = data['Bankrupt?']

# Standardize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

# Create a Gaussian Naive Bayes model
model = GaussianNB()

# Define number of folds
k = 5
# Create a KFold object
kf = KFold(n_splits=k, shuffle=True, random_state=42)

# Perform K-fold cross-validation
cv_scores = cross_val_score(model, X_train, y_train, cv=kf, scoring='accuracy')
cv_recall_scores = cross_val_score(model, X_train, y_train, cv=kf, scoring='recall')

print("Cross-validation Accuracy scores:", cv_scores)
print("Cross-validation Recall scores:", cv_recall_scores)

# Print average results from all folds
average_accuracy = np.mean(cv_scores)
average_recall = np.mean(cv_recall_scores)
print("Average Accuracy:", average_accuracy)
print("Average Recall:", average_recall)

# Fit model on entire training data
model.fit(X_train, y_train)
# Predict on test data
final_predictions = model.predict(X_test)

# Evaluation
accuracy = accuracy_score(y_test, final_predictions)
print("Logistic Regression Model:\n Accuracy:", accuracy)
print("Classification Report:\n", classification_report(y_test, final_predictions))
print("Confusion Matrix:\n", confusion_matrix(y_test, final_predictions))


Cross-validation Accuracy scores: [0.84624846 0.83640836 0.84870849 0.82902829 0.85098522]
Cross-validation Recall scores: [0.85       0.85714286 0.78378378 0.74074074 0.83333333]
Average Accuracy: 0.8422757651221833
Average Recall: 0.8130001430001428
Logistic Regression Model:
 Accuracy: 0.8410786001147447
Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.84      0.91      1681
           1       0.16      0.81      0.27        62

    accuracy                           0.84      1743
   macro avg       0.58      0.82      0.59      1743
weighted avg       0.96      0.84      0.89      1743

Confusion Matrix:
 [[1416  265]
 [  12   50]]
